import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Loading from './loading'
import Navbar from './components/navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
       {/* <Loading/> */}
       <Navbar/>
        {children}
        </body>
    </html>
  )
}
