import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Loading from './loading'
import Navbar from './components/navbar/Navbar'
import myUser from './actions/getUser'
import getBasketItems from './actions/getBasketItems'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default  async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  const myCurrnetUser = await myUser()

  const basketItems= await getBasketItems()
  return (
    <html lang="en">
      <body className={inter.className}>
       {/* <Loading/> */}
       <Navbar 
       basketItems={basketItems}
       myUser={myCurrnetUser}
       />
        {children}
        </body>
    </html>
  )
}
